
version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.18-5
    container_name: "wsl_markoshust_nginx"
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/doggys.conf:/etc/nginx/conf.d/doggys.conf
      - ../nginx/xhprof_html.conf:/etc/nginx/conf.d/xhprof_html.conf
      - ../src-new/:/var/www/html
      - ../xhprof-profiles/:/var/www/xhprof-profiles/
      - ../doggys/:/var/www/html-doggys
      - ../xhprof_html/:/var/www/html-xhprof_html
      - ../xhprof_lib/:/var/www/xhprof_lib
      - ../xdebug-profiling/:/var/www/xdebug-profiling
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

  phpfpm:
    build: ./phpfpm
    container_name: "wsl_markoshust_phpfpm_custom"
#    image: markoshust/magento-php:7.4-fpm-10
#    container_name: "wsl_markoshust_phpfpm"
    links:
      - db
    volumes: *appvolumes
    ports:
      - "22:22"
    expose:
      - 9000
      - 9001
      - 9003
    extra_hosts:
      - "host.internal.docker:host-gateway"

  db:
    build: ./mariadb
    container_name: "wsl_markoshust_mariadb_custom"
#    image: mariadb:10.4
#    container_name: "wsl_markoshust_mariadb"
    command: --max_allowed_packet=2048M --max-heap-table-size=12288M --join-buffer-size=20485760
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:5.0-alpine
    container_name: "wsl_markoshust_redis"

  elasticsearch:
    image: markoshust/magento-elasticsearch:7.9.3-1
    container_name: "wsl_markoshust_elasticsearch"
    hostname: host.docker.internal
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      ## Set custom heap size to avoid memory errors
      - "ES_JAVA_OPTS=-Xms1536m -Xmx1536m"
      ## Avoid test failures due to small disks
      ## More info at https://github.com/markshust/docker-magento/issues/488
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"

  rabbitmq:
    image: rabbitmq:3.8.22-management-alpine
    container_name: "wsl_markoshust_rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    environment:
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=1GB

  mailcatcher:
    image: sj26/mailcatcher
    container_name: "wsl_markoshust_mailcatcher"
    ports:
      - "1080:1080"

  ## Disabling selenium by default as it is not required for all use cases.
  ## For extra_hosts, replace "magento.test" with the URL of your site,
  ## and also replace 172.17.0.1 with the result of:
  ## docker run --rm alpine ip route | awk 'NR==1 {print $3}'
  #selenium:
  #  image: selenium/standalone-chrome-debug:3.8.1
  #  ports:
  #    - "5900:5900"
  #  links:
  #    - app
  #  extra_hosts:
  #    - "magento.test:172.17.0.1"

volumes:
#  appdata:
  dbdata:
  rabbitmqdata:
  sockdata:
  ssldata:
